export const metaKeywords: string[] = [
  'iGOT AI',
  'AI engine creation without coding',
  'Revolutionize AI engine creation',
  'GPT power',
  'Tailor complexity with GPT',
  'Automate routines with AI',
  'Transform business operations with AI',
  'Custom AI engines with GPT',
  'Define complexity effortlessly',
  'Automate tasks with iGOT AI',
  'Execute plans with no coding',
  'Simplify AI engine creation',
  'Empower business with AI',
  'Build custom AI engines',
  'No prompting effort AI',
  'Define, explore, execute AI',
  'Unleash GPT power',
  'AI platform for businesses',
  'AI automation platform',
  'GPT-based AI engine',
  'AI engine builder',
  'Customize AI complexity',
  'AI without coding',
  'AI for business operations',
  'GPT-powered automation',
  'Effortless AI implementation',
  'AI innovation without coding',
  'AI for business transformation',
  'AI engine development made easy',
];
